#spring:
#  application:
#    name: eureka-server
#server:
#  port: 8001
#  tomcat:
#    uri-encoding: utf-8
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false        #注册中心单节点时不需要向注册中心注册自己，设置为false
#    fetch-registry: false              #不需要去检索服务，设置为false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

